# """
#     The MIT License (MIT)

#     Copyright (c) 2023 pkjmesra

#     Permission is hereby granted, free of charge, to any person obtaining a copy
#     of this software and associated documentation files (the "Software"), to deal
#     in the Software without restriction, including without limitation the rights
#     to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#     copies of the Software, and to permit persons to whom the Software is
#     furnished to do so, subject to the following conditions:

#     The above copyright notice and this permission notice shall be included in all
#     copies or substantial portions of the Software.

#     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#     IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#     FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#     AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#     LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#     OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#     SOFTWARE.

# """
# Based on sample from https://github.com/coderabbitai/ai-pr-reviewer

name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
  pull_request_review_comment:
    types: [created]

concurrency:
  group:
    ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: coderabbitai/ai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          # Inspect the messages between OpenAI server
          # Set debug: true in the workflow file to enable debug mode, which will show the messages
          debug: true
          review_simple_changes: true
          review_comment_lgtm: true
          openai_light_model: 'gpt-3.5-turbo'
          openai_heavy_model: 'gpt-3.5-turbo' #'gpt-4'
          system_message: |
            You are `@coderabbitai` (aka `github-actions[bot]`), a language model 
            trained by OpenAI. Your purpose is to act as a highly experienced 
            software engineer and provide a thorough review of the code chunks
            and suggest code snippets to improve key areas such as:
              - Logic
              - Security
              - Code styling issues
              - missing comments or documentation
              - Performance
              - Data races
              - Consistency
              - Error handling
              - Maintainability
              - Modularity
              - Complexity
              - Optimization
              - Best practices: DRY, SOLID, KISS
              - Accuracy
              - Relevance
              - Clarity
              - Technical depth
              - Call-to-action
              - SEO optimization
              - Brand consistency
              - Grammar and prose
              - Typos
              - Hyperlink suggestions
              - Graphics or images (suggest Dall-E image prompts if needed)
              - Empathy
              - Engagement
            
            Identify and resolve significant concerns to improve overall code quality. 
            Knowledge cutoff: 2021-09-01
            Current date: 2024-07-10
            
            IMPORTANT: Entire response must be in the language with ISO code: en-US
            
