# Project             :   Screenipy
# Author              :   Pranjal Joshi
# Created             :   24/01/2022
# Description         :   Workflow for downloading pickled stock data to cloud [Use this when yfinance causing an issue]

name: B. Narrow Range (NRx) Reversal (B_12_6_6)
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Narrow Range (NRx) Reversal (B_12_6_6)'
        required: false
        default: 'Narrow Range (NRx) Reversal (B_12_6_6)'
  schedule:
  - cron: '11 10 * * 1-5'

jobs:

  B_12_6_6:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: Backtest-Reports

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Restore Dependencies from Cache
      uses: actions/cache@v2
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install TA-Lib
      run: |
        python -m pip install --upgrade pip
        cd .github/dependencies/
        echo %cd%
        pip install TA_Lib-0.4.19-cp39-cp39-win_amd64.whl

    - name: Install Python Dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip3 install ta-lib
        pip install .

    - name: Run backtest
      shell: cmd
      run: |
        rmdir /s /q Backtest-Reports
        mkdir Backtest-Reports
        python pkscreener/pkscreenercli.py -a Y -e -p -o B:30:12:6:6:4
        copy "PKScreener_*.html" "Backtest-Reports"

    - name: Push backtest and summary reports
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
        git remote update
        git fetch
        git checkout -b Backtest-Reports origin/Backtest-Reports
        git add Backtest-Reports/PKScreener_*.html --force
        git commit -m "GitHub-Action-Workflow-Backtest-Reports-(B_12_6_6)"
        git push -v -u origin +Backtest-Reports

    - name: Squash Commits (Python)
      shell: cmd
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git fetch
        git checkout -b Backtest-Reports origin/Backtest-Reports
        python .github/workflows/squash.py -b Backtest-Reports -m "GitHub-Action-Workflow-Backtest-Reports-(B_12_6_6)"
