# Project             :   Screenipy
# Author              :   Pranjal Joshi
# Created             :   30/04/2021
# Description         :   Workflow for building pkscreener on pushing a tag

name: pkscreener Build - New Release

on:
  # push:
  #   #branches: [ pre-main ]
  #   tags:
  #     - '*'
  workflow_dispatch:
    inputs:
      branch-name:
        description: 'Branch name'
        required: false
        default: 'main'
  schedule:
    - cron: '55 2 * * 6'

jobs:

  check_should_run:
    runs-on: windows-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: print latest_commit
        run: echo ${{ github.sha }}

      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a week
        if: ${{ github.event_name == 'schedule' }} || ${{ github.event_name == 'workflow_dispatch' }}
        run: test -z $(git rev-list  --after="7 days"  ${{ github.sha }}) && echo "::set-output name=should_run::false"

  # Job for builing packages
  Build:
    name: Build Packages
    needs: check_should_run
    #needs: Create-Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            TARGET: Windows
            CMD_BUILD: |
              pyinstaller --onefile --icon=pkscreener\icon.ico pkscreener\pkscreenercli.py  --hidden-import cmath --hidden-import talib.stream --hidden-import numpy --hidden-import pandas --hidden-import alive-progress --hidden-import alive_progress --hidden-import yfinance
            DEP_BUILD: |
              python -m pip install --upgrade pip
              echo Installing TA-lib...
              cd .github/dependencies/
              echo %cd%
              pip install TA_Lib-0.4.19-cp39-cp39-win_amd64.whl
              cd ..
              cd ..
              python -m pip install --upgrade pip
              pip3 install -r requirements.txt
              pip3 install -r requirements-dev.txt
              pip3 install ta-lib
              pip3 install .
            TEST_BUILD: |
              ./dist/pkscreenercli.exe --testbuild
              exit $?
            OUT_PATH: .\dist\pkscreenercli.exe
            FILE_NAME: pkscreenercli.exe
          
          - os: ubuntu-20.04
            TARGET: Linux
            CMD_BUILD: |
              pyinstaller --onefile --icon=pkscreener/icon.ico pkscreener/pkscreenercli.py  --hidden-import cmath --hidden-import talib.stream --hidden-import numpy --hidden-import pandas --hidden-import alive-progress --hidden-import alive_progress
              mv /home/runner/work/PKScreener/PKScreener/dist/pkscreenercli /home/runner/work/PKScreener/PKScreener/dist/pkscreenercli.bin
              chmod +x /home/runner/work/PKScreener/PKScreener/dist/pkscreenercli.bin
            DEP_BUILD: |
              cd .github/dependencies/
              pwd
              tar -xzf ta-lib-0.4.0-src.tar.gz
              cd ta-lib/
              ./configure --prefix=/usr
              make
              sudo make install
              cd /home/runner/work/PKScreener/PKScreener/
              python -m pip install --upgrade pip
              pip3 install -r requirements.txt
              pip3 install -r requirements-dev.txt
              pip3 install ta-lib==0.4.24
              pip3 install .
            TEST_BUILD: |
              /home/runner/work/PKScreener/PKScreener/dist/pkscreenercli.bin --testbuild
              exit $?
            OUT_PATH: /home/runner/work/PKScreener/PKScreener/dist/pkscreenercli.bin
            FILE_NAME: pkscreenercli.bin

          - os: macos-latest
            TARGET: MacOS
            CMD_BUILD: |
              pyinstaller --onefile --windowed --icon=pkscreener/icon.ico pkscreener/pkscreenercli.py  --hidden-import cmath --hidden-import talib.stream --hidden-import numpy --hidden-import pandas --hidden-import alive-progress --hidden-import alive_progress
              mv /Users/runner/work/PKScreener/PKScreener/dist/pkscreenercli /Users/runner/work/PKScreener/PKScreener/dist/pkscreenercli.run
            DEP_BUILD: |
              brew install ta-lib
              python -m pip install --upgrade pip
              pip3 install -r requirements.txt
              pip3 install -r requirements-dev.txt
              pip3 install ta-lib==0.4.24
              pip3 install .
            TEST_BUILD: |
              /Users/runner/work/PKScreener/PKScreener/dist/pkscreenercli.run --testbuild
              exit $?
            OUT_PATH: /Users/runner/work/PKScreener/PKScreener/dist/pkscreenercli.run
            FILE_NAME: pkscreenercli.run
          
    steps:
      - uses: actions/checkout@v2

      - name: Declare env variables
        id: vars
        shell: bash
        run: |
          GITHUB_REF=${GITHUB_REF#refs/tags/}
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          CURRENT_VERSION=`grep -o "'.*'" pkscreener/classes/__init__.py | sed "s/'//g"`
          VERSION_ARR=(${CURRENT_VERSION//./ })
          MAJOR_MINOR=${VERSION_ARR[0]}.${VERSION_ARR[1]}
          TODAY=`date +%Y%m%d`
          THIS_VERSION=${MAJOR_MINOR}.${TODAY}.${{github.run_number}}
          rm -rf pkscreener/classes/__init__.py
          echo VERSION=\'`echo ${THIS_VERSION}`\' >> pkscreener/classes/__init__.py
          echo "##[set-output name=THIS_VERSION;]$(echo ${THIS_VERSION})"
          echo "##[set-output name=CURRENT_VERSION;]$(echo ${CURRENT_VERSION})"

      - name: Create Tag
        if: startsWith(runner.os, 'Linux')
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add pkscreener/classes/__init__.py --force
            git commit -m "GitHub Action Workflow - Updating version to latest"
            git tag ${{ steps.vars.outputs.THIS_VERSION }} -a -f -m 'Release v${{ steps.vars.outputs.THIS_VERSION }}'
            pip3 install mistletoe
            python .github/workflows/updateVersion.py -p pkscreener/release.md -f /${{ steps.vars.outputs.THIS_VERSION }}/ -r /${{ steps.vars.outputs.THIS_VERSION }}/ -t link
            python .github/workflows/updateVersion.py -p README.md -f /${{ steps.vars.outputs.THIS_VERSION }}/ -r /${{ steps.vars.outputs.THIS_VERSION }}/ -t link
            git push -v --tags

      - name: Get the GitHub Tag version
        id: get_version
        shell: bash
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Load Cache for Linux Dependencies
        uses: actions/cache@v2
        if: startsWith(runner.os, 'Linux')
        with:
          path: |
            /usr/include/ta-lib
            /usr/bin/ta-lib-config
          key: ${{ runner.os }}-talib
          restore-keys: |
            ${{ runner.os }}-talib

      - name: Update ReadME release.md and library version
        if: startsWith(runner.os, 'Linux')
        id: read_release
        shell: bash
        run: |
          python .github/workflows/updateVersion.py -p pkscreener/release.md -f /${{ steps.vars.outputs.THIS_VERSION }}/ -r /${{ steps.vars.outputs.THIS_VERSION }}/ -t link
          r=$(cat pkscreener/release.md)
          r="${r//'%'/'%25'}"
          r="${r//$'\n'/'%0A'}"
          r="${r//$'\r'/'%0D'}"
          echo "::set-output name=RELEASE_BODY::$r"

      - name: Install dependencies for ${{ matrix.TARGET }}
        run: ${{ matrix.DEP_BUILD }}

      - name: Build for ${{ matrix.TARGET }}
        run: ${{ matrix.CMD_BUILD }}

      - name: Test Built Binary for ${{ matrix.TARGET }}
        shell: bash
        run: ${{ matrix.TEST_BUILD }}
        continue-on-error: false

      - name: Save Binaries as Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.FILE_NAME }}
          path: ${{ matrix.OUT_PATH }}

      - name: Upload Binaries to Release
        if: startsWith(github.ref, 'refs/tags') || ${{ needs.check_should_run.outputs.should_run != 'false' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.OUT_PATH }}
          asset_name: ${{ matrix.FILE_NAME }}
          tag: ${{ steps.vars.outputs.THIS_VERSION }}
          release_name: pkscreener - v${{ steps.vars.outputs.THIS_VERSION }}
          body: |
            ${{ steps.read_release.outputs.RELEASE_BODY }}
          overwrite: true
          prerelease: true
          make_latest: false
