# """
#     The MIT License (MIT)

#     Copyright (c) 2023 pkjmesra

#     Permission is hereby granted, free of charge, to any person obtaining a copy
#     of this software and associated documentation files (the "Software"), to deal
#     in the Software without restriction, including without limitation the rights
#     to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#     copies of the Software, and to permit persons to whom the Software is
#     furnished to do so, subject to the following conditions:

#     The above copyright notice and this permission notice shall be included in all
#     copies or substantial portions of the Software.

#     THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#     IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#     FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#     AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#     LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#     OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#     SOFTWARE.

# """
name: B. B_12_20 Backtest for Bullish for next day (B_12_20)
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Backtest for Bullish for next day (B_12_20)'
        required: false
        default: 'Backtest for Bullish for next day (B_12_20)'
  schedule:
  - cron: '30 10 * * 1-5'

jobs:

  B_12_20:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Restore Dependencies from Cache
      uses: actions/cache@v2
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install TA-Lib
      run: |
        python -m pip install --upgrade pip
        cd .github/dependencies/
        echo %cd%
        pip install TA_Lib-0.4.19-cp39-cp39-win_amd64.whl

    - name: Install Python Dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip3 install ta-lib
        pip install .

    - name: Run backtest
      shell: cmd
      continue-on-error: true
      run: |
        rmdir /s /q Backtest-Reports
        mkdir Backtest-Reports
        python pkscreener/pkscreenercli.py -a Y -e -p -o B:30:12:20

    - name: Push backtest and summary reports
      continue-on-error: true
      run: |
        copy "PKScreener_*.html" "Backtest-Reports"
        git config user.name github-actions
        git config user.email github-actions@github.com
        git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
        git remote update
        git fetch
        git checkout -b gh-pages origin/gh-pages
        git pull
        git add Backtest-Reports/PKScreener_B_12_20_backtest_result_StockSorted.html --force
        git add Backtest-Reports/PKScreener_B_12_20_Summary_StockSorted.html --force
        git commit -m "GitHub-Action-Workflow-Backtest-Reports-(B_12_20)"
        git push -v -u origin +gh-pages
